### ISSUE TITLE
Development Proposal: Wallpaper delivery w/ Apollo Server/Graphcool

### ISSUE THREAD

**Issue by retrixe** [RSG-Group/wallpapers#1]
*I'm submitting an issue.*

## Are you requesting a feature or filing a bug?
Feature Request

## What is the current behaviour?
Nothing.

## What is the expected/proposed behaviour?
Basically, I'm thinking this.
We're creating the wallpapers folder where wallpapers + metadata is stored.
Then we have a server folder with an Apollo Server w/ Express inside, which enables our wallpaper client to efficiently fetch wallpapers with Apollo Client.

@radi-cho what do you think, is it worth writing a server to send the wallpapers or do we leave everything to the client? Our client will be significantly slower and lag the user, but it won't require processing power on our side. We can power our server with Graphcool too. It is an easy to use database supporting GraphQL.

Edit 1: We're thinking Graphcool too. It's something which can be considered.

## Please mention your version of Expo XDE (if used), Node.js, your desktop OS version and mobile OS version.

- Expo XDE 
- Node.js 8.4.0
- Ubuntu 17.04 x64
- Android 7.0

**Comment by retrixe** [comment]
Graphcool is super easy to use, what about that? It's awesome.

**Comment by radi-cho** [comment]
OMG! Sorry, dude!!! 😞 You opened this 11 days ago... I didn't view this.
Yes it's good idea to fetch the images...
Maybe you moved it from RSG-Group to your own, because I'm not responding. Sorry guy... I really like this project!

**Comment by retrixe** [comment]
"Sorry, guy"?

**Comment by radi-cho** [comment]
What? '' "Sorry, guy"? ''

**Comment by retrixe** [comment]
Okay, so I'm guessing we should do that.. when I have time.

**Comment by radi-cho** [comment]
Okay

**Comment by retrixe** [comment]
Discussed on Slack, going to close this issue as very old, very useless.
