### ISSUE TITLE
Error: undefined is not an object

### ISSUE THREAD

**Issue by radi-cho** [RSG-Group/wallpapers#2]
### *I'm submitting an issue.* Are you requesting a feature or filing a bug?
Bug... maybe

### What is the current behaviour?
so.. I installed Expo on my phone (and `exp` with yarn 0.27.5) and ran the app (`exp start` in the command line and scanned the QR code with my phone)

#### ... And I got the following error:
![image](https://user-images.githubusercontent.com/12954909/30291135-809a9b3e-973a-11e7-9160-2662d0d7ea27.png)

#### Already did that 
- installed Expo on my phone (and `exp`)
- ran the app
- I got error

### Please mention your version of Expo XDE (if used), Node.js, your desktop OS version and mobile OS version.

- Node.js v8.4.0
- Windows 10.0.15063
- Android 5.1

**Comment by retrixe** [comment]
Yarn 1.0 is here, and try Expo XDE.

**Comment by radi-cho** [comment]
okay... but something about the error?

**Comment by retrixe** [comment]
Confirmed.

**Comment by retrixe** [comment]
This is an issue with stage-0, apparently I forgot to fix it, the patch will be pushed upstream soon.

**Comment by radi-cho** [comment]
cool
